SKILL_SYNONYMS = {
    # Programming Languages
    "js": ["javascript", "ecmascript", "node.js", "nodejs"],
    "javascript": ["js", "ecmascript", "node.js", "nodejs", "vanilla js"],
    "py": ["python", "python3", "python programming"],
    "python": ["py", "python3", "python programming", "python development"],
    "c++": ["cpp", "c plus plus", "cplusplus"],
    "c#": ["csharp", "c sharp", "dotnet", ".net"],
    "java": ["jvm", "java programming", "java development"],
    "php": ["php programming", "hypertext preprocessor"],
    "ruby": ["ruby programming", "rb"],
    "go": ["golang", "google go"],
    "rust": ["rust programming", "rust lang"],
    "typescript": ["ts", "typed javascript"],
    "kotlin": ["kotlin programming", "android kotlin"],
    "swift": ["swift programming", "ios swift"],
    "scala": ["scala programming"],
    "r": ["r programming", "r language", "r statistical"],

    # Frameworks & Libraries
    "react": ["reactjs", "react.js", "react framework"],
    "angular": ["angularjs", "angular.js", "angular framework"],
    "vue": ["vuejs", "vue.js", "vue framework"],
    "django": ["django framework", "django python"],
    "flask": ["flask framework", "flask python"],
    "express": ["expressjs", "express.js", "express framework"],
    "spring": ["spring boot", "spring framework", "spring mvc"],
    "laravel": ["laravel framework", "laravel php"],
    "rails": ["ruby on rails", "ror"],
    "pytorch": ["torch", "pytorch framework", "pytorch deep learning"],
    "tensorflow": ["tf", "tensorflow framework", "tensorflow ml"],
    "keras": ["keras framework", "keras neural network"],
    "scikit-learn": ["sklearn", "scikit learn", "sk-learn"],
    "pandas": ["pandas python", "pandas library"],
    "numpy": ["numpy python", "numerical python"],
    "matplotlib": ["matplotlib python", "pyplot"],
    "seaborn": ["seaborn python", "seaborn visualization"],
    "opencv": ["cv2", "computer vision", "open cv"],

    # Databases
    "sql": ["structured query language", "database query"],
    "mysql": ["my sql", "mysql database"],
    "postgresql": ["postgres", "postgre sql", "psql"],
    "mongodb": ["mongo", "mongo db", "document database"],
    "redis": ["redis cache", "redis database"],
    "sqlite": ["sqlite3", "sqlite database"],
    "oracle": ["oracle db", "oracle database"],
    "cassandra": ["apache cassandra", "cassandra db"],
    "elasticsearch": ["elastic search", "es"],
    "neo4j": ["neo4j graph", "graph database"],

    # Cloud & DevOps
    "aws": ["amazon web services", "aws cloud", "amazon aws"],
    "azure": ["microsoft azure", "azure cloud"],
    "gcp": ["google cloud platform", "google cloud", "gcloud"],
    "docker": ["containerization", "docker container"],
    "kubernetes": ["k8s", "container orchestration", "kube"],
    "jenkins": ["jenkins ci", "jenkins automation"],
    "gitlab": ["gitlab ci", "gitlab cd"],
    "terraform": ["infrastructure as code", "iac"],
    "ansible": ["configuration management", "ansible automation"],
    "chef": ["chef automation", "configuration management"],
    "puppet": ["puppet automation", "configuration management"],

    # Web Technologies
    "html": ["html5", "hypertext markup language", "markup"],
    "css": ["css3", "cascading style sheets", "styling"],
    "sass": ["scss", "syntactically awesome stylesheets"],
    "less": ["less css", "css preprocessor"],
    "bootstrap": ["bootstrap css", "bootstrap framework"],
    "tailwind": ["tailwindcss", "tailwind css"],
    "jquery": ["jquery library", "jquery javascript"],
    "ajax": ["asynchronous javascript", "xmlhttprequest"],
    "json": ["javascript object notation", "data interchange"],
    "xml": ["extensible markup language", "markup language"],
    "rest": ["restful", "rest api", "representational state transfer"],
    "graphql": ["graph ql", "query language"],
    "soap": ["simple object access protocol", "web service"],

    # Testing & Quality
    "junit": ["junit testing", "java testing"],
    "pytest": ["pytest testing", "python testing"],
    "jest": ["jest testing", "javascript testing"],
    "selenium": ["selenium testing", "web automation"],
    "cypress": ["cypress testing", "e2e testing"],
    "postman": ["api testing", "postman testing"],
    "tdd": ["test driven development", "test-driven development"],
    "bdd": ["behavior driven development", "behavior-driven development"],

    # Mobile Development
    "android": ["android development", "android app"],
    "ios": ["ios development", "iphone development"],
    "react native": ["react-native", "rn", "cross-platform mobile"],
    "flutter": ["flutter development", "dart flutter"],
    "xamarin": ["xamarin development", "cross-platform mobile"],

    # Data & Analytics
    "ml": ["machine learning", "artificial intelligence", "ai"],
    "ai": ["artificial intelligence", "machine learning", "ml"],
    "nlp": ["natural language processing", "text processing"],
    "computer vision": ["cv", "image processing", "opencv"],
    "data science": ["data analytics", "data analysis"],
    "big data": ["hadoop", "spark", "data engineering"],
    "etl": ["extract transform load", "data pipeline"],
    "tableau": ["data visualization", "business intelligence"],
    "power bi": ["powerbi", "microsoft bi", "business intelligence"],
    "spark": ["apache spark", "spark processing"],
    "hadoop": ["apache hadoop", "big data"],

    # Methodologies & Practices
    "agile": ["scrum", "kanban", "agile methodology"],
    "scrum": ["agile", "scrum methodology", "scrum framework"],
    "kanban": ["kanban methodology", "lean"],
    "devops": ["dev ops", "continuous integration", "ci/cd"],
    "ci/cd": ["continuous integration", "continuous deployment", "cicd"],
    "microservices": ["micro services", "service-oriented architecture"],
    "mvc": ["model view controller", "architectural pattern"],
    "oop": ["object oriented programming", "object-oriented programming"],
    "functional programming": ["fp", "functional paradigm"],

    # Security
    "cybersecurity": ["cyber security", "information security"],
    "oauth": ["oauth2", "authentication"],
    "jwt": ["json web token", "token authentication"],
    "ssl": ["tls", "secure socket layer", "transport layer security"],
    "penetration testing": ["pen testing", "security testing"],

    # Operating Systems
    "linux": ["unix", "ubuntu", "centos", "debian"],
    "windows": ["microsoft windows", "win"],
    "macos": ["mac os", "osx", "os x"],

    # Version Control
    "git": ["version control", "source control"],
    "github": ["git hub", "code repository"],
    "gitlab": ["git lab", "code repository"],
    "bitbucket": ["bit bucket", "atlassian"],
    "svn": ["subversion", "version control"],

    # Soft Skills
    "leadership": ["team lead", "team leader", "management"],
    "communication": ["verbal communication", "written communication"],
    "teamwork": ["collaboration", "team player"],
    "problem solving": ["troubleshooting", "analytical thinking"],
    "project management": ["pm", "project coordination"],
}